#!/bin/bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install node
brew install mongodb
sudo mkdir -p /data/db
sudo chown -R `id -un` /data/db
npm install --save express-session
npm install --save body-parser
npm install --save multer
